spring:
  application:
    name: SKN Spring Mail

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ///////
    password: ///////
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    test-connection: false
    protocol: smtp
